[tool.poetry]
name = "webint-media"
version = "0.0.54"
description = "manage media on your website"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "AGPL-3.0-or-later"
packages = [{include = "webint_media"}]

[tool.poetry.plugins."webapps"]
media = "webint_media:app"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
webint = ">=0.0"
yt-dlp = "^2023.3.4"

[tool.poetry.group.dev.dependencies]
gmpg = {path="../gmpg", develop=true}
bgq = {path="../bgq", develop=true}
newmath = {path="../newmath", develop=true}
sqlyte = {path="../sqlyte", develop=true}
webagt = {path="../webagt", develop=true}
webint = {path="../webint", develop=true}

# [[tool.poetry.source]]
# name = "main"
# url = "https://ragt.ag/code/pypi"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
