[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mgtron"
authors = [
  { name="Christerpher Hunter", email="chunter@cellantenna.com" },
]
dynamic = ["readme"]
description = "Package for MGTron GUI, a user interface for signal generation"
version = "2.18.0"
requires-python = ">=3.10"
classifiers = [
"Programming Language :: Python :: 3",
"License :: Other/Proprietary License",
"Operating System :: POSIX :: Linux",
]

dependencies = [
"dearpygui>=1.9.1",
"aiosqlite>=0.19.0",
"astroid>=2.15.5",
"attrs>=23.1.0",
"autopep8>=2.0.2",
"beautifultable>=1.1.0",
"bleach>=6.0.0",
"bleuio>=1.2.0",
"build>=0.10.0",
"certifi>=2023.5.7",
"cffi>=1.15.1",
"charset-normalizer>=3.1.0",
"colorama>=0.4.6",
"coverage>=7.2.7",
"cryptography>=41.0.1",
"dill>=0.3.6",
"docstring-to-markdown>=0.12",
"docutils>=0.20.1",
"exceptiongroup>=1.1.1",
"filelock>=3.12.1",
"flake8>=6.0.0",
"idna>=3.4",
"importlib-metadata>=6.6.0",
"iniconfig>=2.0.0",
"isort>=5.12.0",
"jaraco.classes>=3.2.3",
"jedi>=0.18.2",
"jeepney>=0.8.0",
"keyring>=23.13.1",
"lazy-object-proxy>=1.9.0",
"markdown-it-py>=3.0.0",
"mccabe>=0.7.0",
"mdurl>=0.1.2",
"more-itertools>=9.1.0",
"mypy>=1.3.0",
"mypy-extensions>=1.0.0",
"numpy>=1.24.3",
"packaging>=23.1",
"pandas>=2.0.2",
"parso>=0.8.3",
"pkginfo>=1.9.6",
"platformdirs>=3.5.3",
"pluggy>=1.0.0",
"pycodestyle>=2.10.0",
"pycparser>=2.21",
"pydocstyle>=6.3.0",
"pyflakes>=3.0.1",
"Pygments>=2.15.1",
"pylint>=2.17.4",
"pyparsing>=3.0.9",
"pyproject_hooks>=1.0.0",
"pyserial>=3.5",
"pysondb>=1.6.7",
"pytest>=7.3.2",
"pytest-asyncio>=0.21.0",
"pytest-cov>=4.1.0",
"python-dateutil>=2.8.2",
"python-lsp-jsonrpc>=1.0.0",
"python-lsp-server>=1.7.3",
"pytoolconfig>=1.2.5",
"pytz>=2023.3",
"readme-renderer>=37.3",
"requests>=2.31.0",
"requests-toolbelt>=1.0.0",
"rfc3986>=2.0.0",
"rich>=13.4.2",
"rope>=1.8.0",
"SecretStorage>=3.3.3",
"six>=1.16.0",
"snowballstemmer>=2.2.0",
"toml>=0.10.2",
"tomli>=2.0.1",
"tomlkit>=0.11.8",
"twine>=4.0.2",
"typing_extensions>=4.6.3",
"tzdata>=2023.3",
"ujson>=5.8.0",
"urllib3>=2.0.3",
"wcwidth>=0.2.6",
"webencodings>=0.5.1",
"whatthepatch>=1.0.5",
"wrapt>=1.15.0",
"yapf>=0.33.0",
"zipp>=3.15.0",
"python-decouple>=3.8",
]

[tool.setuptools.dynamic]
readme = {file = ["README.md", "CHANGELOG.md"]}

[project.optional-dependencies]
test = [
"pytest>=7.3.2",
"pytest-asyncio>=0.21.0",
"pytest-cov>=4.1.0"
]

[project.urls]
"Source" = "https://github.com/cellantenna/mg_tron"

[project.gui-scripts]
mgtron = "src.main:main"

[tools.setuptools]
include-package-data = "True"

[tool.setuptools.packages.find]
namespaces = true
where = ["."]

[tool.setuptools.package-data]
"*" = [
"*.ini",
"*.sql",
"*.db",
"*.json",
"*.lock",
"*.ttf",
"*.log",
"*.rst",
"*.txt",
"*.cpy",
"assets",
]