[tool.poetry]
name = "bring-order"
version = "v0.3.1"
description = ""
authors = ["BringOrder team"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.3.1"
invoke = "^2.1.2"
ipywidgets = "^8.0.6"
display = "^1.0.0"
notebook = "^6.5.4"
py2nb = "^1.0.0"
playwright = "^1.35.0"
npx = "^0.1.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pylint = "^2.17.4"
coverage = "^7.2.5"
robotframework = "^6.0.2"
robotframework-seleniumlibrary = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
