[tool.poetry]
name = "delphai-fastapi"
version = "0.1.3"
description = "Package for fastAPI models"
authors = ["Berinike Tech <berinike@delphai.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95"
fastapi-camelcase = "^1.0.5"
delphai-utils = {version = "^3", extras = ["config"]}
bson = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
pep8-naming = "*"
black = "^21.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
