[build-system]
requires = ["hatchling", "pandas", "Bio", "scipy", "numpy", "matplotlib"]
build-backend = "hatchling.build"

[project]
name = "fastq2folder"
version = "1.0.3"
authors = [
  { name="Elizabeth Gardner", email="egar18111@gmail.com" },
]
description = "Script to process fastq files before epi2me analysis"
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"