[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "TINTOlib"
version = "0.0.14"
authors = [
    { name="BorjaRei", email="borjareinoso@gmail.com" },
    { name= "manwestc", email="jcastillo@fi.upm.es"}
]
description = "Converting tabular data into images"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/BorjaRei/TINTOlib"
